# Generated by Django 4.2 on 2023-05-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eveniment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eveniment',
            name='description',
        ),
    ]
