# Generated by Django 4.2 on 2023-05-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eveniment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveniment',
            name='eveniment_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
