# Generated by Django 4.2 on 2023-05-08 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_eveniment_eveniment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, verbose_name='Nume')),
                ('prenume', models.CharField(max_length=120, verbose_name='Prenume')),
                ('eveniment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eveniment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
