# Generated by Django 4.2 on 2023-05-19 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_prietenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveniment',
            name='eveniment_create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data creare eveniment'),
        ),
        migrations.AddField(
            model_name='eveniment',
            name='eveniment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data eveniment'),
        ),
        migrations.AddField(
            model_name='eveniment',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eveniment',
            name='tickets',
            field=models.TextField(blank=True),
        ),
    ]
