# Generated by Django 4.2 on 2023-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='funds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(default='user', max_length=120, verbose_name='Role'),
        ),
    ]
