# Generated by Django 4.2 on 2023-05-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_appuser_funds_appuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eveniment',
            old_name='manager',
            new_name='organiser',
        ),
        migrations.AddField(
            model_name='eveniment',
            name='ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
