# Generated by Django 4.2 on 2023-05-26 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_rename_manager_eveniment_organiser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilet',
            name='eveniment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eveniment'),
        ),
        migrations.AlterField(
            model_name='bilet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
