# Generated by Django 4.2 on 2023-05-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_appuser_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilet',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name='Cadou'),
        ),
    ]
