# Generated by Django 4.2 on 2023-05-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_bilet_is_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveniment',
            name='initial_tickets',
            field=models.TextField(blank=True),
        ),
    ]
