# Generated by Django 4.2 on 2023-05-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_delete_event_delete_myclubuser_delete_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveniment',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Locatie'),
        ),
    ]
