# Generated by Django 4.2 on 2023-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_eveniment_prediction_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilet',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data vanzare bilet'),
        ),
    ]
