# Generated by Django 4.2 on 2023-06-13 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0027_alter_friendrequest_user1_alter_friendrequest_user2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eveniment',
            new_name='Event',
        ),
    ]
