# Generated by Django 4.2 on 2023-06-13 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0028_rename_eveniment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='eveniment_create_date',
            field=models.DateTimeField(verbose_name='Data creare eveniment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eveniment_date',
            field=models.DateTimeField(verbose_name='Data eveniment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='initial_tickets',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.TextField(),
        ),
    ]
