# Generated by Django 4.2 on 2023-06-14 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0030_rename_bilet_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prietenie',
            new_name='Friendship',
        ),
    ]
